version: "3.7"

services:
  mongo:
    image: bitnami/mongodb:4.4-debian-10
    container_name: ${APP_NAME}
    hostname: ${APP_NAME}
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=123456789
      - MONGODB_USERNAME=user
      - MONGODB_DATABASE=test
      - MONGODB_PASSWORD=123456789
